### ISSUE TITLE
数据库可以换成MySQL吗

### ISSUE THREAD

**Issue by towelong** [meloalright/guora#14]
一直用mysql

**Comment by meloalright** [comment]
> 一直用mysql

会接下来支持多种 db 选项

**Comment by towelong** [comment]
> > 一直用mysql
> 
> 会接下来支持多种 db 选项

好的期待你的项目更新

**Comment by meloalright** [comment]
> > > 一直用mysql
> > 
> > 
> > 会接下来支持多种 db 选项
> 
> 好的期待你的项目更新

目前 beta5 版本已经支持 mysql 和 postgres
