### ISSUE TITLE
哈喽，前端部分不开源吗

### ISSUE THREAD

**Issue by linuxempire** [meloalright/guora#18]

**Comment by meloalright** [comment]
前端代码开源还要等一段时间 会在本仓库的 release candidate 之后 #3

**Comment by meloalright** [comment]
> _No description provided._

前端代码开源还要等一段时间 会在本仓库的 release candidate 之后 #3

**Comment by songheng45** [comment]
好想等到前端代码

**Comment by meloalright** [comment]
> 好想等到前端代码

有的 就在这 🤣 https://github.com/meloalright/guora/issues/3

**Comment by meloalright** [comment]
> > 好想等到前端代码
> 
> 有的 就在这 🤣 #3

@songheng45
