### ISSUE TITLE
删除问题有Bug;支持 Markdown;支持 i18n

### ISSUE THREAD

**Issue by Jonnyan404** [meloalright/guora#2]
1. 删除问题,还需要删除所有回复,才能不在主页面展示?
2. 不支持注册
3. 不支持markdown
4. 不支持中文

---

待完成度,还差很多啊,不过还是支持一下!

**Comment by Jonnyan404** [comment]
体验版命令（已支持arm64/amd64）: 
`docker run -d --name guora -p 8080:8080 jonnyan404/guora`

- 登录账号:admin@localhost
- 登录密码:mypassword

**Comment by meloalright** [comment]
> 1. 删除问题,还需要删除所有回复,才能不在主页面展示?
> 2. 不支持注册
> 3. 不支持markdown
> 4. 不支持中文
> 
> 待完成度,还差很多啊,不过还是支持一下!

首页删除问题那个确实是问题🤔 接下来会解决下

注册那个 现在是只支持管理员手动后台添加用户

很多模块还很简易 会逐渐丰富起来

**Comment by meloalright** [comment]
> 体验版命令:
> `docker run -d --name guora -p 8080:8080 jonnyan404/guora`
> 
> * 登录账号:admin@localhost
> * 登录密码:mypassword

删除问题的 bug 已经修复了 可以体验一下

```shell
$ docker run -d --name guora -p 8080:8080 meloalright/guora:beta
```

**Comment by Jonnyan404** [comment]
1. 全局页面中文语言选项
2. 全局支持 markdown 语法
3. 添加用户手动注册
4. 添加LDAP支持

**Comment by meloalright** [comment]
> 1. 全局页面中文语言选项
> 2. 全局支持 markdown 语法
> 3. 添加用户手动注册
> 4. 添加LDAP支持

走心了 同样欢迎 PR ~

**Comment by meloalright** [comment]
> 1. 删除问题,还需要删除所有回复,才能不在主页面展示?
> 2. 不支持注册
> 3. 不支持markdown
> 4. 不支持中文
> 
> 待完成度,还差很多啊,不过还是支持一下!

👏🏻 beta2 版本已经支持简体中文 在 `conf/configuration.yaml` 中如下配置即可

```yaml
lang: zh
```

**Comment by meloalright** [comment]
删除的问题 + i18n 目前版本都是已解决了 🎉

Markdown 编辑未来会作为一个可配置选项支持 #25
