### ISSUE TITLE
大大您好，请问有演示站点吗？

### ISSUE THREAD

**Issue by jay-mars** [meloalright/guora#26]
非常喜欢您的作品

**Comment by meloalright** [comment]
现在木有演示站点 推荐通过 README 当中的 [development-non-dockerized-deploy](https://github.com/meloalright/guora#development-non-dockerized-deploy) 作为参考从零开始启动哈

**Comment by jay-mars** [comment]
go mod download 里面的地址似乎失效了，大大您看看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: meloalright ***@***.***&gt;
发送时间: 2021年5月16日 23:32
收件人: meloalright/guora ***@***.***&gt;
抄送: M4RS ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[meloalright/guora] 大大您好，请问有演示站点吗？ (#26)





 
现在木有演示站点 推荐通过 README 当中的 development-non-dockerized-deploy 作为参考从零开始启动哈

**Comment by jay-mars** [comment]
大大，在执行&nbsp;go mod download&nbsp;的时候 出现：



这是什么问题呀

**Comment by meloalright** [comment]
> go mod download 里面的地址似乎失效了，大大您看看 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: meloalright ***@***.***&gt; 发送时间: 2021年5月16日 23:32 收件人: meloalright/guora ***@***.***&gt; 抄送: M4RS ***@***.***&gt;, Author ***@***.***&gt; 主题: 回复：[meloalright/guora] 大大您好，请问有演示站点吗？ (#26) 现在木有演示站点 推荐通过 README 当中的 development-non-dockerized-deploy 作为参考从零开始启动哈 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

@jay-mars 你好哈童鞋 报错信息是什么 可以贴出来看看嘛

**Comment by meloalright** [comment]
> 大大，在执行&nbsp;go mod download&nbsp;的时候 出现： 这是什么问题呀

出现的是什么😂 可以提供下嘛 @jay-mars
