### ISSUE TITLE
Source code for ui

### ISSUE THREAD

**Issue by kounelios13** [meloalright/guora#3]
Hello. Is there any way we can have the source code for the ui (not just the generated javascript bundles) so we can play a little bit around?

**Comment by meloalright** [comment]
> Hello. Is there any way we can have the source code for the ui (not just the generated javascript bundles) so we can play a little bit around?

Yeah, the UI source code is coming soon, in fact that the UI source code is not so good right now, even very bad.
Maybe 2 weeks later :D

**Comment by yanzeqinglf** [comment]
期待ui

**Comment by unstppbl** [comment]
Nihao there! Can you open the ui code now? I'm very curious about it :)

**Comment by meloalright** [comment]
On the Gitlab
[https://gitlab.com/meloalright/guora-website](https://gitlab.com/meloalright/guora-website)
