### ISSUE TITLE
Setting CreatedAt on updates 

### ISSUE THREAD

**Issue by cchanningallen** [meloalright/guora#7]
https://github.com/meloalright/guora/blob/9e4096bcf6fd6a7840a486bfefb25f9170ce7aaa/model/base.go#L16

Should this be setting UpdatedAt, instead of CreatedAt?

Nice work on the project!

**Comment by meloalright** [comment]
> https://github.com/meloalright/guora/blob/9e4096bcf6fd6a7840a486bfefb25f9170ce7aaa/model/base.go#L16
> 
> Should this be setting UpdatedAt, instead of CreatedAt?
> 
> Nice work on the project!

Yeah.. That is bug

**Comment by meloalright** [comment]
> https://github.com/meloalright/guora/blob/9e4096bcf6fd6a7840a486bfefb25f9170ce7aaa/model/base.go#L16
> 
> Should this be setting UpdatedAt, instead of CreatedAt?
> 
> Nice work on the project!

Bug fixed
